### ISSUE TITLE
Selectable 'this' reference

### ISSUE THREAD

**Issue by Clashsoft** [Dyvil/Dyvil#104]
Add the possibility to select which instance of `this` is requested using subscript syntax:

```java
abstract class Foo
class Outer
{
    static Foo foo = new Foo { String toString() = this[Outer].toString }
}
```

**Comment by SamTebbs33** [comment]
When would there be different "this" instances?

**Comment by Clashsoft** [comment]
The inner class usually has to 'capture' the enclosing instance, to make fields available. I updated the example to make it more clear.
