### ISSUE TITLE
Extension Classes

### ISSUE THREAD

**Issue by Clashsoft** [Dyvil/Dyvil#304]
Add language support for Extension classes, a lightweight way to extend pre-existing classes. Their goal is to remove the burden of choosing between `static`, `infix` and `extension` and allowing static extension methods.

Extension classes are a purely additive feature and are considered syntactic sugar. They are not decompiled from bytecode.

For now, it is a non-goal to be able to add new stored properties to existing classes. Under the hood, these would have to be implemented using weak identity hash maps. The standard library currently does not provide this functionality. Until this is available or a better implementation approach is found, extension classes will not support stored properties. Computed properties are supported and can be used to implement the functionality manually.

# Example

``` swift
// StringExts.dyh

extension String
{
    static func apply(value: any): String = value.toString

    func size(): int = this.length
}

// becomes

class StringExts$String
{
    // This form does not have the same method resolution semantics as the above
    static func apply(this: String, value: any): String = ...

    // postfix instead of extension because String is final
    postfix func size(_this: String) = _this.length
}
```

By importing the `StringExts` header into scope, the following expressions become valid:

``` swift
var s1 = String(value: 10)

type Str = String
var s2 = Str(value: 10) // not possible with method named 'String'

var size = s1.size // behaves like an infix method
```

# Generic Extensions

Extension Classes allow the use of generics to extend generic class. The following example illustrates the syntax and transformation when generics are used:

```swift
// ListExts.dyh

extension<type T> List<T>
{
    func reserve() -> List<T> = ...
}

// becomes

class ListExts$List
{
    extension func reserve<type T>(_this: List<T>) -> List<T> = ...
}
```

As shown in the example, generic type parameter lists are simply copied to the method(s) in the body. A consequence of this is that extension classes allow reified generic type parameters. However, it should be noted that this may interfere with dynamic extension method resolution.

# Grammar

The grammar of an Extension Class can be described as:

``` sh
extensionClass : { modifier | annotation }? 'extension' typeParameters? type classBody
```

**Comment by phase** [comment]
Do we need a name for the extension class? Ruby allows you to just "open" the class, which I think looks a lot nicer.

Something like

```java
extension String {
    public static func apply(any value): String = value.toString

    public func size(): int = this.length
}
```

This is a lot cleaner than having three more tokens.

**Comment by Clashsoft** [comment]
@phase I already considered that, but the reason for the extra tokens is availability. If I put your example in a header `Foo` in a package `bar`, which other classes/headers have access to the extensions? The ones in the same header, in the same package, in the same module, or even those that merely reference the module (by import or by compiler library dependency)? With an extra name, you can choose to make the extensions available by adding an `import` declaration.

**Comment by Clashsoft** [comment]
@phase Update: I have revisited the idea of extension classes and determined that they should indeed not have a name. You can import them together with their enclosing header file.
