### ISSUE TITLE
Installer for Windows?

### ISSUE THREAD

**Issue by Qwerp-Derp** [Dyvil/Dyvil#340]
Is there a plan to make a Windows installer for Dyvil that sets up the language (i.e. sets up the system environment variables, places the executables in a suitable folder, etc.) so that it can be easily used? If not, can you put a user guide for installing and using the language on the main README.md?

**Comment by Clashsoft** [comment]
Currently not planned for any OS, but I will make a short guide on how to try out the different tools and put it in the README.
